[workspace]
authors = ["Federico Aprile <fgaprile@ucdavis.edu>"]
channels = ["conda-forge"]
name = "libbot_bert"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[tasks.ollama-serve]
cmd = "ollama serve"
env.OLLAMA_MODELS = "/dsl/libbot/data/ollama_cache"

[tasks.ollama-pull]
cmd = "ollama pull"
env.OLLAMA_MODELS = "/dsl/libbot/data/ollama_cache"

[tasks.ollama-list]
cmd = "ollama list"
env.OLLAMA_MODELS = "/dsl/libbot/data/ollama_cache"

[tasks.ollama-run]
cmd = "ollama run"
env.OLLAMA_MODELS = "/dsl/libbot/data/ollama_cache"

[tasks.ollama-rm]
cmd = "ollama rm"
env.OLLAMA_MODELS = "/dsl/libbot/data/ollama_cache"

[dependencies]
python = "==3.10"
numpy = "*"
pandas = "*"
pytorch = "*"
transformers = "*"
sentence-transformers = "*"
pyarrow = "<14"
einops = ">=0.8.1,<0.9"
ollama-python = "*"
chromadb = ">=1.2.1,<2"
psutil = ">=7.2.1,<8"
scikit-learn = ">=1.7.2,<2"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
pydantic = ">=2.12.5,<3"
fastapi = ">=0.115.9,<0.116"
pydantic-settings = ">=2.13.0,<3"
uvicorn = ">=0.41.0,<0.42"
httpx = ">=0.28.1,<0.29"
ollama = ">=0.20.4,<0.21"
jupyter = ">=1.1.1,<2"
ipykernel = ">=7.2.0,<8"
nltk = ">=3.9.3,<4"
numactl = ">=2.0.18,<3"






